"""adult module

Revision ID: 0e4b1bc3e0ae
Revises: dcb20c7c2abd
Create Date: 2026-09-20 18:09:56.696535

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '0e4b1bc3e0ae'
down_revision: str | None = 'dcb20c7c2abd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_summary_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('week_mask', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_summary_configs_user_id'), 'daily_summary_configs', ['user_id'], unique=False)
    op.create_table('shopping_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('qty', sa.String(length=80), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purchased', sa.Boolean(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_ref', sa.String(length=120), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_items_purchased_at'), 'shopping_items', ['purchased_at'], unique=False)
    op.create_index(op.f('ix_shopping_items_user_id'), 'shopping_items', ['user_id'], unique=False)
    op.create_table('summary_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_summary_exception_day')
    )
    op.create_index(op.f('ix_summary_exceptions_date'), 'summary_exceptions', ['date'], unique=False)
    op.create_index(op.f('ix_summary_exceptions_user_id'), 'summary_exceptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summary_exceptions_user_id'), table_name='summary_exceptions')
    op.drop_index(op.f('ix_summary_exceptions_date'), table_name='summary_exceptions')
    op.drop_table('summary_exceptions')
    op.drop_index(op.f('ix_shopping_items_user_id'), table_name='shopping_items')
    op.drop_index(op.f('ix_shopping_items_purchased_at'), table_name='shopping_items')
    op.drop_table('shopping_items')
    op.drop_index(op.f('ix_daily_summary_configs_user_id'), table_name='daily_summary_configs')
    op.drop_table('daily_summary_configs')
    # ### end Alembic commands ###