"""menu comidas

Revision ID: 787fe4318d13
Revises: 7eef35a00cda
Create Date: 2026-09-23 20:10:14.221839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import UTC, datetime


revision: str = '787fe4318d13'
down_revision: Union[str, None] = '7eef35a00cda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_slot_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('default_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'slot', name='uq_slot_config_user_slot')
    )
    op.create_index(op.f('ix_meal_slot_configs_user_id'), 'meal_slot_configs', ['user_id'], unique=False)
    op.create_table('recipe_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_recipe_category_user_name')
    )
    op.create_index(op.f('ix_recipe_categories_user_id'), 'recipe_categories', ['user_id'], unique=False)
    op.create_table('category_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_category_id', sa.Integer(), nullable=False),
    sa.Column('min_per_week', sa.Integer(), nullable=False),
    sa.Column('max_per_week', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_category_id'], ['recipe_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recipe_category_id', name='uq_goal_user_category')
    )
    op.create_index(op.f('ix_category_goals_recipe_category_id'), 'category_goals', ['recipe_category_id'], unique=False)
    op.create_index(op.f('ix_category_goals_user_id'), 'category_goals', ['user_id'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('slots_mask', sa.SmallInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['recipe_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_user_id'), 'recipes', ['user_id'], unique=False)
    op.create_table('meal_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('slot', sa.String(length=16), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('free_text', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', 'slot', name='uq_meal_plan_day_slot')
    )
    op.create_index(op.f('ix_meal_plans_date'), 'meal_plans', ['date'], unique=False)
    op.create_index(op.f('ix_meal_plans_user_id'), 'meal_plans', ['user_id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ingredients_recipe_id'), 'recipe_ingredients', ['recipe_id'], unique=False)
    # --- seed de categorías globales por defecto (user_id NULL) ---
    categories = sa.table(
        "recipe_categories",
        sa.column("user_id", sa.Integer),
        sa.column("name", sa.String),
        sa.column("order", sa.Integer),
        sa.column("created_at", sa.DateTime),
    )
    now = datetime.now(UTC)
    op.bulk_insert(
        categories,
        [
            {"user_id": None, "name": "pescado", "order": 1, "created_at": now},
            {"user_id": None, "name": "verdura", "order": 2, "created_at": now},
            {"user_id": None, "name": "legumbre", "order": 3, "created_at": now},
            {"user_id": None, "name": "carne", "order": 4, "created_at": now},
            {"user_id": None, "name": "huevo", "order": 5, "created_at": now},
            {"user_id": None, "name": "pasta/arroz", "order": 6, "created_at": now},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_ingredients_recipe_id'), table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index(op.f('ix_meal_plans_user_id'), table_name='meal_plans')
    op.drop_index(op.f('ix_meal_plans_date'), table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_index(op.f('ix_recipes_user_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_category_goals_user_id'), table_name='category_goals')
    op.drop_index(op.f('ix_category_goals_recipe_category_id'), table_name='category_goals')
    op.drop_table('category_goals')
    op.drop_index(op.f('ix_recipe_categories_user_id'), table_name='recipe_categories')
    op.drop_table('recipe_categories')
    op.drop_index(op.f('ix_meal_slot_configs_user_id'), table_name='meal_slot_configs')
    op.drop_table('meal_slot_configs')
    # ### end Alembic commands ###