"""notify push subs + outbox

Revision ID: 7eef35a00cda
Revises: 0e4b1bc3e0ae
Create Date: 2026-09-23 18:57:05.047240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7eef35a00cda'
down_revision: Union[str, None] = '0e4b1bc3e0ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ref', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_outbox_due_at'), 'notification_outbox', ['due_at'], unique=False)
    op.create_index(op.f('ix_notification_outbox_next_retry_at'), 'notification_outbox', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_notification_outbox_user_id'), 'notification_outbox', ['user_id'], unique=False)
    op.create_index('ix_outbox_status_due', 'notification_outbox', ['status', 'due_at'], unique=False)
    op.create_index('ix_outbox_status_retry', 'notification_outbox', ['status', 'next_retry_at'], unique=False)
    op.create_index('uq_outbox_pending_ref', 'notification_outbox', ['user_id', 'ref'], unique=True, postgresql_where=sa.text("status='pending'"), sqlite_where=sa.text("status='pending'"))
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index('uq_outbox_pending_ref', table_name='notification_outbox', postgresql_where=sa.text("status='pending'"), sqlite_where=sa.text("status='pending'"))
    op.drop_index('ix_outbox_status_retry', table_name='notification_outbox')
    op.drop_index('ix_outbox_status_due', table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_user_id'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_next_retry_at'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_due_at'), table_name='notification_outbox')
    op.drop_table('notification_outbox')
    # ### end Alembic commands ###