"""motor de tareas: rooms, subjects, tasks, ajustes users

Revision ID: a0e613d8764c
Revises: 5f8d11596d63
Create Date: 2026-09-19 21:29:27.111072

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'a0e613d8764c'
down_revision: str | None = '5f8d11596d63'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect

    bind = op.get_bind()
    insp = inspect(bind)
    users_cols = {c["name"] for c in insp.get_columns("users")}
    if "display_name" not in users_cols:
        op.add_column('users', sa.Column('display_name', sa.String(length=80), nullable=True))
    if "updated_at" not in users_cols:
        # SQLite admite NOT NULL solo con DEFAULT constante de texto.
        op.add_column(
            'users',
            sa.Column(
                'updated_at',
                sa.DateTime(timezone=True),
                nullable=False,
                server_default='2026-09-19 00:00:00',
            ),
        )
    # SQLite no soporta ALTER de tipo: reconstruir la tabla con el nuevo length.
    with op.batch_alter_table('users') as batch:
        batch.alter_column(
            'profile_type',
            existing_type=sa.VARCHAR(length=16),
            type_=sa.String(length=8),
            existing_nullable=False,
        )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_user_id'), 'rooms', ['user_id'], unique=False)
    op.create_table('rotation_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('rec_interval', sa.Integer(), nullable=False),
    sa.Column('rec_unit', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rotation_groups_user_id'), 'rotation_groups', ['user_id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('days_resumen', sa.Integer(), nullable=False),
    sa.Column('days_estudio', sa.Integer(), nullable=False),
    sa.Column('days_practica', sa.Integer(), nullable=False),
    sa.Column('days_repaso', sa.Integer(), nullable=False),
    sa.Column('include_weekends', sa.Boolean(), nullable=False),
    sa.Column('resumen_total_pages', sa.Integer(), nullable=True),
    sa.Column('resumen_done_pages', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_user_id'), 'subjects', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notify', sa.Boolean(), nullable=False),
    sa.Column('rec_type', sa.String(length=16), nullable=True),
    sa.Column('rec_interval', sa.Integer(), nullable=False),
    sa.Column('rec_unit', sa.String(length=8), nullable=True),
    sa.Column('rec_week_mask', sa.SmallInteger(), nullable=False),
    sa.Column('rec_day_of_month', sa.SmallInteger(), nullable=True),
    sa.Column('rec_anchor', sa.Date(), nullable=True),
    sa.Column('rec_next_due', sa.Date(), nullable=True),
    sa.Column('rotation_group_id', sa.Integer(), nullable=True),
    sa.Column('rotation_index', sa.SmallInteger(), nullable=True),
    sa.Column('pending_from_class', sa.Boolean(), nullable=False),
    sa.Column('est_minutes', sa.Integer(), nullable=True),
    sa.Column('done_minutes', sa.Integer(), nullable=False),
    sa.Column('last_done_on', sa.Date(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rotation_group_id'], ['rotation_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_category'), 'tasks', ['category'], unique=False)
    op.create_index(op.f('ix_tasks_rec_next_due'), 'tasks', ['rec_next_due'], unique=False)
    op.create_index(op.f('ix_tasks_rec_type'), 'tasks', ['rec_type'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('task_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('done_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'done_on', name='uq_task_done')
    )
    op.create_index(op.f('ix_task_completions_done_on'), 'task_completions', ['done_on'], unique=False)
    op.create_index(op.f('ix_task_completions_task_id'), 'task_completions', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch:
        batch.alter_column(
            'profile_type',
            existing_type=sa.String(length=8),
            type_=sa.VARCHAR(length=16),
            existing_nullable=False,
        )
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'display_name')
    op.drop_index(op.f('ix_task_completions_task_id'), table_name='task_completions')
    op.drop_index(op.f('ix_task_completions_done_on'), table_name='task_completions')
    op.drop_table('task_completions')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_rec_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_rec_next_due'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_category'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_subjects_user_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_rotation_groups_user_id'), table_name='rotation_groups')
    op.drop_table('rotation_groups')
    op.drop_index(op.f('ix_rooms_user_id'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###