"""checkin_configs

Revision ID: dcb20c7c2abd
Revises: 6248dac4c79a
Create Date: 2026-09-20 17:22:04.088470

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'dcb20c7c2abd'
down_revision: str | None = '6248dac4c79a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkin_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('week_mask', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkin_configs_user_id'), 'checkin_configs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkin_configs_user_id'), table_name='checkin_configs')
    op.drop_table('checkin_configs')
    # ### end Alembic commands ###